### PR TITLE
Adjusts CMake version to match tag

### PR DESCRIPTION
**Pull request by loriab**
I'm opening this PR so I don't forget about this branch. But no call to merge it yet, as there'll probably be more changes before the thing's actually working.

### CODE REVIEW

**Comment by edeprince3** [comment]
OK, keep me posted!

**Comment by loriab** [comment]
When you get a chance, hop over to https://travis-ci.org/profile/edeprince3 and toggle ON the v2rdm_casscf repo, please.

**Comment by edeprince3** [comment]
Do I need to do anything else besides toggling this repo on at travis-ci?  Is this ready to merge?

**Comment by loriab** [comment]
* Just toggle for now; that will enable travis to do it's work when the `.travis.yml` file from this repo gets merged in.
* Not quite yet for merging (also, it'll need a rebase). I've got building working on travis but not testing yet.
* If the idea works for you, I'll prep this as if you'll do a `0.7` tag for psi4 1.2

**Comment by edeprince3** [comment]
Sounds good.

**Comment by loriab** [comment]
FYI, I won't turn on codecov because it'd just cover the python and that's not representative. I've got a ticket into the conda folks to add `gcov` to their compiler packages, and after that I'll get it working for psi locally and after that it'll trickle to v2rdm.

**Comment by loriab** [comment]
Ok, you should be good to merge. Note that you'll need a really recent (last few days) version of psi4 to really use local plugin options after an options clean.

**Comment by loriab** [comment]
ping!

I'll be brave and advise merge-and-tag `v0.7`

**Comment by edeprince3** [comment]
Ping acknowledged.  I will try to do this in the next hour.

**Comment by loriab** [comment]
thanks! here's tagging commands, in case you like crutches as I do. http://psicode.org/psi4manual/master/manage_git.html#how-to-create-and-remove-an-annotated-git-tag-on-a-remote

**Comment by edeprince3** [comment]
Thanks, @loriab !  I bumped the tag up to v0.7

**Pull request merged**
