### PR TITLE
Update __init__.py.in

### PR DESCRIPTION
**Pull request by loriab**
Be convenient but less heavy-handed.

### CODE REVIEW

**Comment by loriab** [comment]
@edeprince3, have you built this thing with g++/gfortran lately? It's just fine with Intel, but when I use GCC, it complains on all the fortran files. The `gfortran.bin` file it doesn't seem to like is in `PATH`. Trouble is very possibly with conda GCC, but I'd like to know if GNU is supported as a compiler.

```
[  2%] Building Fortran object CMakeFiles/v2rdm_casscf.dir/focas_diis.F90.o
/home/psilocaluser/toolchainconda/envs/v2test/bin/x86_64-conda_cos6-linux-gnu-gfortran -DHAVE_OPENMP -Dv2rdm_casscf_EXPORTS -I/home/psilocaluser/toolchainconda/envs/v2test/include -I/home/psilocaluser/toolchainconda/envs/v2test/include/python3.6m  --sysroot=/home/psilocaluser/toolchainconda/envs/v2test/x86_64-conda_cos6-linux-gnu/sysroot NOTFOUND -fPIC   -fvisibility=hidden -std=c++11 -c /home/psilocaluser/gits/v2rdm_casscf/focas_diis.F90 -o CMakeFiles/v2rdm_casscf.dir/focas_diis.F90.o
x86_64-conda_cos6-linux-gnu-gfortran.bin: error: NOTFOUND: No such file or directory
make[2]: *** [CMakeFiles/v2rdm_casscf.dir/focas_diis.F90.o] Error 1
make[2]: Leaving directory `/home/psilocaluser/gits/v2rdm_casscf/build-gcc'
make[1]: *** [CMakeFiles/v2rdm_casscf.dir/all] Error 2
make[1]: Leaving directory `/home/psilocaluser/gits/v2rdm_casscf/build-gcc'
make: *** [all] Error 2
```

**Comment by loriab** [comment]
nevermind, that was a false solution, as I still had all the Fortran files not building. nevertheless, _did_ find the real problem, which was `-fopenmp` masquerading as the generic `NOTFOUND`, hence the (in retrospect) very logical error above. solution not found, but I can at least blame my own cmake rather than conda complier config (though they're a bit to blame for not providing omp module for gfortran) or your code.

**Comment by edeprince3** [comment]
I built downloaded a fresh copy of this repository on my Mac and built with gnu with no problem.  I'm having more general psi4 issues on my other machines and haven't tested the gnu build there, though.

**Comment by loriab** [comment]
Ok, update on this. GNU is indeed fine, but fixing the conda gnu fortran issue (so that travis will build, which is where my whole investigation started) led to a generalization of the new openmp handling, for which a PR (to psi4) is close but not imminent (I'm letting my cmake rage cool a bit from yesterday). Another PR to this is coming.

**Pull request merged**
